SELECT DISTINCT c.CAR_ID, c.CAR_TYPE, FLOOR(c.DAILY_FEE * 30 * (100 - d.DISCOUNT_RATE) / 100) as FEE
FROM CAR_RENTAL_COMPANY_CAR as c
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN as d
    ON c.CAR_TYPE = d.CAR_TYPE AND DURATION_TYPE = '30일 이상'
WHERE c.CAR_ID NOT IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01'
)
    AND c.CAR_TYPE IN ('세단', 'SUV')
GROUP BY c.CAR_ID
HAVING 500000 <= FEE AND FEE < 2000000
ORDER BY FEE DESC, c.CAR_TYPE, c.CAR_ID DESC


-- WHERE c.CAR_ID NOT IN (
--     SELECT CAR_ID
--     FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
--     WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01'
-- )
-- 위 부분이 필요한 이유?
-- 단순 조건절로 날짜를 제외하면 history 목록에서 해당 기록만 제외하는 결과를 낳기 때문